# Task 11
## Indexing and Slicing

In [4]:
import numpy as np

n = np.array([[1,2,3,4,5,6],[4,5,6,7,8,9],[7,8,9,4,3,2],[3,13,6,9,12,1],[3,24,5,12,20,7],[2,3,7,21,18,23]])
print(n[0:2, 0:2])


[[1 2]
 [4 5]]


In [5]:
n1 = np.array([[[1], [4]], [[2], [5]], [[3], [7]]])
print(n1[:2, :, 0])

[[1 4]
 [2 5]]


In [6]:
n2 = np.array((1,2,3,4,5,7,9))
ind = [1,3,4,6]
print(n2[ind])

[2 4 5 9]


In [7]:
n3 = np.array([[3,5,7,2],[4,16,20,11],[17,6,8,9], [4,5,6,1]])
rows = [0,2]
cols = [1,3]
print(n3[rows, cols])

[5 9]


In [8]:
n4 = np.array((1,2,3,4,5,7,9, 2,28,20)) 
print(n4[n4>8])

[ 9 28 20]


In [9]:
n5 = np.array([[1,2,3,14,5,16],[4,5,6,7,8,9],[7,8,9,4,3,2],[3,13,6,9,12,1],[3,24,5,12,20,7],[2,3,7,21,18,23]])
n5[n5>13] = 0
print(n5)

[[ 1  2  3  0  5  0]
 [ 4  5  6  7  8  9]
 [ 7  8  9  4  3  2]
 [ 3 13  6  9 12  1]
 [ 3  0  5 12  0  7]
 [ 2  3  7  0  0  0]]


## Broadcasting 

In [10]:
n = np.array((1,2,3))
n1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n +n1)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [11]:
n = np.array((1,2,3))
n1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n*n1)

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


In [12]:
n = np.array([[1],[4],[7]])
n1 = np.array([[1,4,7,2]])
print(n+n1)

[[ 2  5  8  3]
 [ 5  8 11  6]
 [ 8 11 14  9]]


In [13]:
array = np.array([[[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]],
                     
                     [[13, 14, 15, 16],
                      [17, 18, 19, 20],
                      [21, 22, 23, 24]]])


array1 = np.array([[1, 2, 1, 4],
                     [9, 8, 5, 1],
                     [10, 11, 6, 2]])

print(array+array1)

[[[ 2  4  4  8]
  [14 14 12  9]
  [19 21 17 14]]

 [[14 16 16 20]
  [26 26 24 21]
  [31 33 29 26]]]
